### ISSUE TITLE
Field aliasing via delegated schema not remapping field names

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-graphql#164]
api: https://cardano-graphql-mainnet.daedalus-operations.com/

```graphql
query test {
  blocks (limit: 1, order_by: { createdAt: desc}) {
    blockHash: id # alias id to blockHash
    epochNo
    slotWithinEpoch
    slotNo
    createdAt
  }
}
```

```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Block.id.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "blocks",
        0,
        "blockHash"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Block.id.",
            "    at completeValue (/application/node_modules/graphql/execution/execute.js:560:13)",
            "    at completeValueCatchingError (/application/node_modules/graphql/execution/execute.js:495:19)",
            "    at resolveField (/application/node_modules/graphql/execution/execute.js:435:10)",
            "    at executeFields (/application/node_modules/graphql/execution/execute.js:275:18)",
            "    at collectAndExecuteSubfields (/application/node_modules/graphql/execution/execute.js:713:10)",
            "    at completeObjectValue (/application/node_modules/graphql/execution/execute.js:703:10)",
            "    at completeValue (/application/node_modules/graphql/execution/execute.js:591:12)",
            "    at completeValueCatchingError (/application/node_modules/graphql/execution/execute.js:495:19)",
            "    at /application/node_modules/graphql/execution/execute.js:618:25",
            "    at Array.forEach (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": {
    "blocks": [
      null
    ]
  }
}
```

**Comment by rhyslbw** [comment]
Sorry for the delay in response @islishude

Reopening, as it's a bug I need to investigate. The expectation is for the aliases to be remapped after the delegated response is returned from Hasura, since `makeRemoteExecutableSchema` should handle this.   

On a side-node, the specific alias you're making here should be addressed in #175

**Comment by dingxiangfei2009** [comment]
Hello, @islishude and @rhyslbw. It seems that this issue still persists for `cardano-graphql@5.1.0`. Here is a sample query to reproduce it.

```graphql
query (
  $where: Epoch_bool_exp
){
  epochs( where: $where ) {
    protocolParams {
      feeFixed: minFeeA
      feePerByte:minFeeB
    }
  }
}
```
The error message is the following.
```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field ShelleyProtocolParams.minFeeA.",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "epochs",
        0,
        "protocolParams",
        "feeFixed"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field ShelleyProtocolParams.minFeeA.",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:560:13)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:495:19)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:435:10)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:275:18)",
            "    at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:713:10)",
            "    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:703:10)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:591:12)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:495:19)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:435:10)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:275:18)"
          ]
        }
      }
    }
  ],
  "data": {
    "epochs": [
      {
        "protocolParams": null
      }
    ]
  }
}
```

**Comment by dingxiangfei2009** [comment]
This issue may be the culprit. ardatan/graphql-tools#3267

**Comment by rhyslbw** [comment]
Sorry @dingxiangfei2009 , this shouldn't have been closed. We'll see if the library author has an ideas

**Comment by islishude** [comment]
I will close this issue since it doesn't have any activities any more.

IF YOU NEED IT, PLEASE FILE A NEW ONE.
